# MY_SQL - Asia/Seoul
driverName=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://mysql-rds.cdss8ci22ly8.ap-northeast-2.rds.amazonaws.com:3306/shell_hero?serverTimezone=UTC
userName=admin
userPass=shell1234!